import { describe, expect, it } from "vitest";

import {
  isValidPresetName,
  MAX_PRESET_NAME_LENGTH,
  normalizePresetName,
  updatePresetNameDraft,
  type PresetNameDraft,
} from "./presetName";

function draft(value = ""): PresetNameDraft {
  return { value, whitespaceRunEnds: [] };
}

describe("presetName", () => {
  it("normalizes full typed or pasted values into lowercase whitespace slugs", () => {
    expect(normalizePresetName("Nice One")).toBe("nice-one");
    expect(normalizePresetName("  Nice\t \nOne  More")).toBe(
      "nice-one-more",
    );
  });

  it("preserves literal slug punctuation and unsupported visible characters", () => {
    expect(normalizePresetName("Already--_Fine")).toBe("already--_fine");
    expect(normalizePresetName("Okay?!É")).toBe("okay?!É");
  });

  it("does not truncate and validates both slug shape and maximum length", () => {
    const atLimit = "a".repeat(MAX_PRESET_NAME_LENGTH);
    const overLimit = `${atLimit}a`;

    expect(normalizePresetName(overLimit)).toHaveLength(
      MAX_PRESET_NAME_LENGTH + 1,
    );
    expect(isValidPresetName(atLimit)).toBe(true);
    expect(isValidPresetName(overLimit)).toBe(false);
    expect(isValidPresetName("warm-1_a")).toBe(true);
    expect(isValidPresetName("Warm")).toBe(false);
    expect(isValidPresetName("../escape")).toBe(false);
    expect(isValidPresetName("has space")).toBe(false);
    expect(isValidPresetName("")).toBe(false);
  });

  it("keeps separately typed repeated whitespace in one generated hyphen", () => {
    let current = updatePresetNameDraft(draft("nice"), "nice ");
    expect(current).toEqual({ value: "nice-", whitespaceRunEnds: [5] });

    current = updatePresetNameDraft(current, "nice- ");
    expect(current).toEqual({ value: "nice-", whitespaceRunEnds: [5] });

    current = updatePresetNameDraft(current, "nice-o");
    expect(current).toEqual({ value: "nice-o", whitespaceRunEnds: [] });
  });

  it("discards separately typed leading whitespace as one tracked run", () => {
    let current = updatePresetNameDraft(draft(), " ");
    expect(current).toEqual({ value: "", whitespaceRunEnds: [0] });

    current = updatePresetNameDraft(current, "   ");
    expect(current).toEqual({ value: "", whitespaceRunEnds: [0] });

    current = updatePresetNameDraft(current, "N");
    expect(current).toEqual({ value: "n", whitespaceRunEnds: [] });
  });

  it("preserves genuine literal hyphen runs around generated delimiters", () => {
    let current = updatePresetNameDraft(draft("a"), "a--");
    expect(current).toEqual({ value: "a--", whitespaceRunEnds: [] });

    current = updatePresetNameDraft(current, "a-- ");
    expect(current).toEqual({ value: "a---", whitespaceRunEnds: [4] });

    current = updatePresetNameDraft(current, "a--- ");
    expect(current).toEqual({ value: "a---", whitespaceRunEnds: [4] });
  });

  it("extends whitespace runs generated by a paste without duplicating hyphens", () => {
    let trailing = updatePresetNameDraft(draft(), "Nice ");
    expect(trailing).toEqual({ value: "nice-", whitespaceRunEnds: [5] });
    trailing = updatePresetNameDraft(trailing, "nice- ");
    expect(trailing).toEqual({ value: "nice-", whitespaceRunEnds: [5] });

    let middle = updatePresetNameDraft(draft(), "Nice One More");
    expect(middle).toEqual({
      value: "nice-one-more",
      whitespaceRunEnds: [5, 9],
    });
    middle = updatePresetNameDraft(middle, "nice- one-more");
    expect(middle).toEqual({
      value: "nice-one-more",
      whitespaceRunEnds: [5, 9],
    });
  });
});
